gfcli:
  gen:
    enums:
      src: "api"
      path: "internal/boot/boot_enums.go"
    dao:
      - link:            "mysql:root:123456@tcp(192.168.1.14:3306)/sms"
        jsonCase:        "Snake"
        tablesEx: "casbin_rule,sys_auth_rule,sys_config,sys_dept,sys_dict_data,sys_dict_type,sys_login_log,sys_oper_log,sys_post,sys_role,sys_role_dept,sys_user,sys_user_online,sys_user_post"
        descriptionTag:  true
        noModelComment:  false
        path: "./internal"
  run:
    path: "./bin"
    watchPaths:
      - api/*.go
      - internal/controller/*.go
  build:
    arch: "amd64"
    system: "linux"
    mod: "none"
    packSrc: "resource,manifest"
    version: "v1.0.0"
    output: "./bin/sms_backend"
    extra: "-ldflags '-w -s'"