gfcli:
  gen:
    dao:
      - link:            "mysql:root:Baizhe@2024@tcp(127.0.0.1:33062)/upay"
        jsonCase:        "Snake"
        tablesEx: "casbin_rule,sys_auth_rule,sys_config,sys_dept,sys_dict_data,sys_dict_type,sys_login_log,sys_oper_log,sys_post,sys_role,sys_role_dept,sys_user,sys_user_online,sys_user_post"
        descriptionTag:  true
        noModelComment:  false
        path: "./internal"
