// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package v1

import (
	"sms_backend/api/v1"
)

type ControllerCommon struct{}

func NewCommon() v1.IV1Common {
	return &ControllerCommon{}
}

type ControllerSms struct{}

func NewSms() v1.IV1Sms {
	return &ControllerSms{}
}

type ControllerSystem struct{}

func NewSystem() v1.IV1System {
	return &ControllerSystem{}
}

type ControllerCareer struct{}

func NewCareer() v1.IV1Career {
	return &ControllerCareer{}
}
