// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package v1

import (
	"sms_backend/api/v1"
)

type ControllerCommon struct{}

func NewCommon() v1.IV1Common {
	return &ControllerCommon{}
}

type ControllerSms struct{}

func NewSms() v1.IV1Sms {
	return &ControllerSms{}
}

type ControllerSystem struct{}

func NewSystem() v1.IV1System {
	return &ControllerSystem{}
}

type ControllerCareer struct{}

func NewCareer() v1.IV1Career {
	return &ControllerCareer{}
}

type ControllerUser struct{}

func NewUser() v1.IV1User {
	return &ControllerUser{}
}

type ControllerSubUser struct{}

func NewSubUser() v1.IV1SubUser {
	return &ControllerSubUser{}
}

type ControllerAllUser struct{}

func NewAllUser() v1.IV1AllUser {
	return &ControllerAllUser{}
}

type ControllerLog struct{}

func NewLog() v1.IV1Log {
	return &ControllerLog{}
}

type ControllerRole struct{}

func NewRole() v1.IV1Role {
	return &ControllerRole{}
}
