// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalAccountImportFailsDao is internal type for wrapping internal DAO implements.
type internalAccountImportFailsDao = *internal.AccountImportFailsDao

// accountImportFailsDao is the data access object for table account_import_fails.
// You can define custom methods on it to extend its functionality as you wish.
type accountImportFailsDao struct {
	internalAccountImportFailsDao
}

var (
	// AccountImportFails is globally public accessible object for table account_import_fails operations.
	AccountImportFails = accountImportFailsDao{
		internal.NewAccountImportFailsDao(),
	}
)

// Fill with you ideas below.
