// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalAccountGroupDao is internal type for wrapping internal DAO implements.
type internalAccountGroupDao = *internal.AccountGroupDao

// accountGroupDao is the data access object for table account_group.
// You can define custom methods on it to extend its functionality as you wish.
type accountGroupDao struct {
	internalAccountGroupDao
}

var (
	// AccountGroup is globally public accessible object for table account_group operations.
	AccountGroup = accountGroupDao{
		internal.NewAccountGroupDao(),
	}
)

// Fill with you ideas below.
