// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalAccountLinkDeviceDao is internal type for wrapping internal DAO implements.
type internalAccountLinkDeviceDao = *internal.AccountLinkDeviceDao

// accountLinkDeviceDao is the data access object for table account_link_device.
// You can define custom methods on it to extend its functionality as you wish.
type accountLinkDeviceDao struct {
	internalAccountLinkDeviceDao
}

var (
	// AccountLinkDevice is globally public accessible object for table account_link_device operations.
	AccountLinkDevice = accountLinkDeviceDao{
		internal.NewAccountLinkDeviceDao(),
	}
)

// Fill with you ideas below.
