// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalAllocationTaskFailsDao is internal type for wrapping internal DAO implements.
type internalAllocationTaskFailsDao = *internal.AllocationTaskFailsDao

// allocationTaskFailsDao is the data access object for table allocation_task_fails.
// You can define custom methods on it to extend its functionality as you wish.
type allocationTaskFailsDao struct {
	internalAllocationTaskFailsDao
}

var (
	// AllocationTaskFails is globally public accessible object for table allocation_task_fails operations.
	AllocationTaskFails = allocationTaskFailsDao{
		internal.NewAllocationTaskFailsDao(),
	}
)

// Fill with you ideas below.
