// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalApkSetDao is internal type for wrapping internal DAO implements.
type internalApkSetDao = *internal.ApkSetDao

// apkSetDao is the data access object for table apk_set.
// You can define custom methods on it to extend its functionality as you wish.
type apkSetDao struct {
	internalApkSetDao
}

var (
	// ApkSet is globally public accessible object for table apk_set operations.
	ApkSet = apkSetDao{
		internal.NewApkSetDao(),
	}
)

// Fill with you ideas below.
