// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalAppGroupDao is internal type for wrapping internal DAO implements.
type internalAppGroupDao = *internal.AppGroupDao

// appGroupDao is the data access object for table app_group.
// You can define custom methods on it to extend its functionality as you wish.
type appGroupDao struct {
	internalAppGroupDao
}

var (
	// AppGroup is globally public accessible object for table app_group operations.
	AppGroup = appGroupDao{
		internal.NewAppGroupDao(),
	}
)

// Fill with you ideas below.
