// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalAppUserDetailDao is internal type for wrapping internal DAO implements.
type internalAppUserDetailDao = *internal.AppUserDetailDao

// appUserDetailDao is the data access object for table app_user_detail.
// You can define custom methods on it to extend its functionality as you wish.
type appUserDetailDao struct {
	internalAppUserDetailDao
}

var (
	// AppUserDetail is globally public accessible object for table app_user_detail operations.
	AppUserDetail = appUserDetailDao{
		internal.NewAppUserDetailDao(),
	}
)

// Fill with you ideas below.
