// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalAppLabelDao is internal type for wrapping internal DAO implements.
type internalAppLabelDao = *internal.AppLabelDao

// appLabelDao is the data access object for table app_label.
// You can define custom methods on it to extend its functionality as you wish.
type appLabelDao struct {
	internalAppLabelDao
}

var (
	// AppLabel is globally public accessible object for table app_label operations.
	AppLabel = appLabelDao{
		internal.NewAppLabelDao(),
	}
)

// Fill with you ideas below.
