// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalAppUserDao is internal type for wrapping internal DAO implements.
type internalAppUserDao = *internal.AppUserDao

// appUserDao is the data access object for table app_user.
// You can define custom methods on it to extend its functionality as you wish.
type appUserDao struct {
	internalAppUserDao
}

var (
	// AppUser is globally public accessible object for table app_user operations.
	AppUser = appUserDao{
		internal.NewAppUserDao(),
	}
)

// Fill with you ideas below.
