// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalCardLevelDao is internal type for wrapping internal DAO implements.
type internalCardLevelDao = *internal.CardLevelDao

// cardLevelDao is the data access object for table card_level.
// You can define custom methods on it to extend its functionality as you wish.
type cardLevelDao struct {
	internalCardLevelDao
}

var (
	// CardLevel is globally public accessible object for table card_level operations.
	CardLevel = cardLevelDao{
		internal.NewCardLevelDao(),
	}
)

// Fill with you ideas below.
