// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalCasbinRule20240906Dao is internal type for wrapping internal DAO implements.
type internalCasbinRule20240906Dao = *internal.CasbinRule20240906Dao

// casbinRule20240906Dao is the data access object for table casbin_rule_20240906.
// You can define custom methods on it to extend its functionality as you wish.
type casbinRule20240906Dao struct {
	internalCasbinRule20240906Dao
}

var (
	// CasbinRule20240906 is globally public accessible object for table casbin_rule_20240906 operations.
	CasbinRule20240906 = casbinRule20240906Dao{
		internal.NewCasbinRule20240906Dao(),
	}
)

// Fill with you ideas below.
