// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalChatTaskLinkDeviceDao is internal type for wrapping internal DAO implements.
type internalChatTaskLinkDeviceDao = *internal.ChatTaskLinkDeviceDao

// chatTaskLinkDeviceDao is the data access object for table chat_task_link_device.
// You can define custom methods on it to extend its functionality as you wish.
type chatTaskLinkDeviceDao struct {
	internalChatTaskLinkDeviceDao
}

var (
	// ChatTaskLinkDevice is globally public accessible object for table chat_task_link_device operations.
	ChatTaskLinkDevice = chatTaskLinkDeviceDao{
		internal.NewChatTaskLinkDeviceDao(),
	}
)

// Fill with you ideas below.
