// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalChatTaskLinkCollectDataGroupDao is internal type for wrapping internal DAO implements.
type internalChatTaskLinkCollectDataGroupDao = *internal.ChatTaskLinkCollectDataGroupDao

// chatTaskLinkCollectDataGroupDao is the data access object for table chat_task_link_collect_data_group.
// You can define custom methods on it to extend its functionality as you wish.
type chatTaskLinkCollectDataGroupDao struct {
	internalChatTaskLinkCollectDataGroupDao
}

var (
	// ChatTaskLinkCollectDataGroup is globally public accessible object for table chat_task_link_collect_data_group operations.
	ChatTaskLinkCollectDataGroup = chatTaskLinkCollectDataGroupDao{
		internal.NewChatTaskLinkCollectDataGroupDao(),
	}
)

// Fill with you ideas below.
