// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalClientFundFlowDao is internal type for wrapping internal DAO implements.
type internalClientFundFlowDao = *internal.ClientFundFlowDao

// clientFundFlowDao is the data access object for table client_fund_flow.
// You can define custom methods on it to extend its functionality as you wish.
type clientFundFlowDao struct {
	internalClientFundFlowDao
}

var (
	// ClientFundFlow is globally public accessible object for table client_fund_flow operations.
	ClientFundFlow = clientFundFlowDao{
		internal.NewClientFundFlowDao(),
	}
)

// Fill with you ideas below.
