// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalClientLabelDao is internal type for wrapping internal DAO implements.
type internalClientLabelDao = *internal.ClientLabelDao

// clientLabelDao is the data access object for table client_label.
// You can define custom methods on it to extend its functionality as you wish.
type clientLabelDao struct {
	internalClientLabelDao
}

var (
	// ClientLabel is globally public accessible object for table client_label operations.
	ClientLabel = clientLabelDao{
		internal.NewClientLabelDao(),
	}
)

// Fill with you ideas below.
