// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalCollectTaskLinkDeviceGroupDao is internal type for wrapping internal DAO implements.
type internalCollectTaskLinkDeviceGroupDao = *internal.CollectTaskLinkDeviceGroupDao

// collectTaskLinkDeviceGroupDao is the data access object for table collect_task_link_device_group.
// You can define custom methods on it to extend its functionality as you wish.
type collectTaskLinkDeviceGroupDao struct {
	internalCollectTaskLinkDeviceGroupDao
}

var (
	// CollectTaskLinkDeviceGroup is globally public accessible object for table collect_task_link_device_group operations.
	CollectTaskLinkDeviceGroup = collectTaskLinkDeviceGroupDao{
		internal.NewCollectTaskLinkDeviceGroupDao(),
	}
)

// Fill with you ideas below.
