// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalCollectTaskLinkDeviceDao is internal type for wrapping internal DAO implements.
type internalCollectTaskLinkDeviceDao = *internal.CollectTaskLinkDeviceDao

// collectTaskLinkDeviceDao is the data access object for table collect_task_link_device.
// You can define custom methods on it to extend its functionality as you wish.
type collectTaskLinkDeviceDao struct {
	internalCollectTaskLinkDeviceDao
}

var (
	// CollectTaskLinkDevice is globally public accessible object for table collect_task_link_device operations.
	CollectTaskLinkDevice = collectTaskLinkDeviceDao{
		internal.NewCollectTaskLinkDeviceDao(),
	}
)

// Fill with you ideas below.
