// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalCollectDataGroupDao is internal type for wrapping internal DAO implements.
type internalCollectDataGroupDao = *internal.CollectDataGroupDao

// collectDataGroupDao is the data access object for table collect_data_group.
// You can define custom methods on it to extend its functionality as you wish.
type collectDataGroupDao struct {
	internalCollectDataGroupDao
}

var (
	// CollectDataGroup is globally public accessible object for table collect_data_group operations.
	CollectDataGroup = collectDataGroupDao{
		internal.NewCollectDataGroupDao(),
	}
)

// Fill with you ideas below.
