// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalDataImportsDao is internal type for wrapping internal DAO implements.
type internalDataImportsDao = *internal.DataImportsDao

// dataImportsDao is the data access object for table data_imports.
// You can define custom methods on it to extend its functionality as you wish.
type dataImportsDao struct {
	internalDataImportsDao
}

var (
	// DataImports is globally public accessible object for table data_imports operations.
	DataImports = dataImportsDao{
		internal.NewDataImportsDao(),
	}
)

// Fill with you ideas below.
