// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalDevicePriceDao is internal type for wrapping internal DAO implements.
type internalDevicePriceDao = *internal.DevicePriceDao

// devicePriceDao is the data access object for table device_price.
// You can define custom methods on it to extend its functionality as you wish.
type devicePriceDao struct {
	internalDevicePriceDao
}

var (
	// DevicePrice is globally public accessible object for table device_price operations.
	DevicePrice = devicePriceDao{
		internal.NewDevicePriceDao(),
	}
)

// Fill with you ideas below.
