// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalDevicePriceOpDao is internal type for wrapping internal DAO implements.
type internalDevicePriceOpDao = *internal.DevicePriceOpDao

// devicePriceOpDao is the data access object for table device_price_op.
// You can define custom methods on it to extend its functionality as you wish.
type devicePriceOpDao struct {
	internalDevicePriceOpDao
}

var (
	// DevicePriceOp is globally public accessible object for table device_price_op operations.
	DevicePriceOp = devicePriceOpDao{
		internal.NewDevicePriceOpDao(),
	}
)

// Fill with you ideas below.
