// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalDeviceGrantImportFailsDao is internal type for wrapping internal DAO implements.
type internalDeviceGrantImportFailsDao = *internal.DeviceGrantImportFailsDao

// deviceGrantImportFailsDao is the data access object for table device_grant_import_fails.
// You can define custom methods on it to extend its functionality as you wish.
type deviceGrantImportFailsDao struct {
	internalDeviceGrantImportFailsDao
}

var (
	// DeviceGrantImportFails is globally public accessible object for table device_grant_import_fails operations.
	DeviceGrantImportFails = deviceGrantImportFailsDao{
		internal.NewDeviceGrantImportFailsDao(),
	}
)

// Fill with you ideas below.
