// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalDeviceLinkLabelDao is internal type for wrapping internal DAO implements.
type internalDeviceLinkLabelDao = *internal.DeviceLinkLabelDao

// deviceLinkLabelDao is the data access object for table device_link_label.
// You can define custom methods on it to extend its functionality as you wish.
type deviceLinkLabelDao struct {
	internalDeviceLinkLabelDao
}

var (
	// DeviceLinkLabel is globally public accessible object for table device_link_label operations.
	DeviceLinkLabel = deviceLinkLabelDao{
		internal.NewDeviceLinkLabelDao(),
	}
)

// Fill with you ideas below.
