// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalDeviceBindHistoryDao is internal type for wrapping internal DAO implements.
type internalDeviceBindHistoryDao = *internal.DeviceBindHistoryDao

// deviceBindHistoryDao is the data access object for table device_bind_history.
// You can define custom methods on it to extend its functionality as you wish.
type deviceBindHistoryDao struct {
	internalDeviceBindHistoryDao
}

var (
	// DeviceBindHistory is globally public accessible object for table device_bind_history operations.
	DeviceBindHistory = deviceBindHistoryDao{
		internal.NewDeviceBindHistoryDao(),
	}
)

// Fill with you ideas below.
