// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalDeviceChatDao is internal type for wrapping internal DAO implements.
type internalDeviceChatDao = *internal.DeviceChatDao

// deviceChatDao is the data access object for table device_chat.
// You can define custom methods on it to extend its functionality as you wish.
type deviceChatDao struct {
	internalDeviceChatDao
}

var (
	// DeviceChat is globally public accessible object for table device_chat operations.
	DeviceChat = deviceChatDao{
		internal.NewDeviceChatDao(),
	}
)

// Fill with you ideas below.
