// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalDeviceRemarksDao is internal type for wrapping internal DAO implements.
type internalDeviceRemarksDao = *internal.DeviceRemarksDao

// deviceRemarksDao is the data access object for table device_remarks.
// You can define custom methods on it to extend its functionality as you wish.
type deviceRemarksDao struct {
	internalDeviceRemarksDao
}

var (
	// DeviceRemarks is globally public accessible object for table device_remarks operations.
	DeviceRemarks = deviceRemarksDao{
		internal.NewDeviceRemarksDao(),
	}
)

// Fill with you ideas below.
