// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalDeviceLabelDao is internal type for wrapping internal DAO implements.
type internalDeviceLabelDao = *internal.DeviceLabelDao

// deviceLabelDao is the data access object for table device_label.
// You can define custom methods on it to extend its functionality as you wish.
type deviceLabelDao struct {
	internalDeviceLabelDao
}

var (
	// DeviceLabel is globally public accessible object for table device_label operations.
	DeviceLabel = deviceLabelDao{
		internal.NewDeviceLabelDao(),
	}
)

// Fill with you ideas below.
