// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalDeviceGrantDao is internal type for wrapping internal DAO implements.
type internalDeviceGrantDao = *internal.DeviceGrantDao

// deviceGrantDao is the data access object for table device_grant.
// You can define custom methods on it to extend its functionality as you wish.
type deviceGrantDao struct {
	internalDeviceGrantDao
}

var (
	// DeviceGrant is globally public accessible object for table device_grant operations.
	DeviceGrant = deviceGrantDao{
		internal.NewDeviceGrantDao(),
	}
)

// Fill with you ideas below.
