// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalDeviceListDao is internal type for wrapping internal DAO implements.
type internalDeviceListDao = *internal.DeviceListDao

// deviceListDao is the data access object for table device_list.
// You can define custom methods on it to extend its functionality as you wish.
type deviceListDao struct {
	internalDeviceListDao
}

var (
	// DeviceList is globally public accessible object for table device_list operations.
	DeviceList = deviceListDao{
		internal.NewDeviceListDao(),
	}
)

// Fill with you ideas below.
