// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalEntDeviceLinkLabelDao is internal type for wrapping internal DAO implements.
type internalEntDeviceLinkLabelDao = *internal.EntDeviceLinkLabelDao

// entDeviceLinkLabelDao is the data access object for table ent_device_link_label.
// You can define custom methods on it to extend its functionality as you wish.
type entDeviceLinkLabelDao struct {
	internalEntDeviceLinkLabelDao
}

var (
	// EntDeviceLinkLabel is globally public accessible object for table ent_device_link_label operations.
	EntDeviceLinkLabel = entDeviceLinkLabelDao{
		internal.NewEntDeviceLinkLabelDao(),
	}
)

// Fill with you ideas below.
