// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalEntPlatformDao is internal type for wrapping internal DAO implements.
type internalEntPlatformDao = *internal.EntPlatformDao

// entPlatformDao is the data access object for table ent_platform.
// You can define custom methods on it to extend its functionality as you wish.
type entPlatformDao struct {
	internalEntPlatformDao
}

var (
	// EntPlatform is globally public accessible object for table ent_platform operations.
	EntPlatform = entPlatformDao{
		internal.NewEntPlatformDao(),
	}
)

// Fill with you ideas below.
