// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalEntSysDictTypeDao is internal type for wrapping internal DAO implements.
type internalEntSysDictTypeDao = *internal.EntSysDictTypeDao

// entSysDictTypeDao is the data access object for table ent_sys_dict_type.
// You can define custom methods on it to extend its functionality as you wish.
type entSysDictTypeDao struct {
	internalEntSysDictTypeDao
}

var (
	// EntSysDictType is globally public accessible object for table ent_sys_dict_type operations.
	EntSysDictType = entSysDictTypeDao{
		internal.NewEntSysDictTypeDao(),
	}
)

// Fill with you ideas below.
