// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalEntSysRoleDeptDao is internal type for wrapping internal DAO implements.
type internalEntSysRoleDeptDao = *internal.EntSysRoleDeptDao

// entSysRoleDeptDao is the data access object for table ent_sys_role_dept.
// You can define custom methods on it to extend its functionality as you wish.
type entSysRoleDeptDao struct {
	internalEntSysRoleDeptDao
}

var (
	// EntSysRoleDept is globally public accessible object for table ent_sys_role_dept operations.
	EntSysRoleDept = entSysRoleDeptDao{
		internal.NewEntSysRoleDeptDao(),
	}
)

// Fill with you ideas below.
