// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalEntSysOperLogDao is internal type for wrapping internal DAO implements.
type internalEntSysOperLogDao = *internal.EntSysOperLogDao

// entSysOperLogDao is the data access object for table ent_sys_oper_log.
// You can define custom methods on it to extend its functionality as you wish.
type entSysOperLogDao struct {
	internalEntSysOperLogDao
}

var (
	// EntSysOperLog is globally public accessible object for table ent_sys_oper_log operations.
	EntSysOperLog = entSysOperLogDao{
		internal.NewEntSysOperLogDao(),
	}
)

// Fill with you ideas below.
