// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalEntSysDeptDao is internal type for wrapping internal DAO implements.
type internalEntSysDeptDao = *internal.EntSysDeptDao

// entSysDeptDao is the data access object for table ent_sys_dept.
// You can define custom methods on it to extend its functionality as you wish.
type entSysDeptDao struct {
	internalEntSysDeptDao
}

var (
	// EntSysDept is globally public accessible object for table ent_sys_dept operations.
	EntSysDept = entSysDeptDao{
		internal.NewEntSysDeptDao(),
	}
)

// Fill with you ideas below.
