// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalEntSysDictDataDao is internal type for wrapping internal DAO implements.
type internalEntSysDictDataDao = *internal.EntSysDictDataDao

// entSysDictDataDao is the data access object for table ent_sys_dict_data.
// You can define custom methods on it to extend its functionality as you wish.
type entSysDictDataDao struct {
	internalEntSysDictDataDao
}

var (
	// EntSysDictData is globally public accessible object for table ent_sys_dict_data operations.
	EntSysDictData = entSysDictDataDao{
		internal.NewEntSysDictDataDao(),
	}
)

// Fill with you ideas below.
