// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalEntSysConfigDao is internal type for wrapping internal DAO implements.
type internalEntSysConfigDao = *internal.EntSysConfigDao

// entSysConfigDao is the data access object for table ent_sys_config.
// You can define custom methods on it to extend its functionality as you wish.
type entSysConfigDao struct {
	internalEntSysConfigDao
}

var (
	// EntSysConfig is globally public accessible object for table ent_sys_config operations.
	EntSysConfig = entSysConfigDao{
		internal.NewEntSysConfigDao(),
	}
)

// Fill with you ideas below.
