// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalEntSysUserOnlineDao is internal type for wrapping internal DAO implements.
type internalEntSysUserOnlineDao = *internal.EntSysUserOnlineDao

// entSysUserOnlineDao is the data access object for table ent_sys_user_online.
// You can define custom methods on it to extend its functionality as you wish.
type entSysUserOnlineDao struct {
	internalEntSysUserOnlineDao
}

var (
	// EntSysUserOnline is globally public accessible object for table ent_sys_user_online operations.
	EntSysUserOnline = entSysUserOnlineDao{
		internal.NewEntSysUserOnlineDao(),
	}
)

// Fill with you ideas below.
