// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalEntDeviceLabelDao is internal type for wrapping internal DAO implements.
type internalEntDeviceLabelDao = *internal.EntDeviceLabelDao

// entDeviceLabelDao is the data access object for table ent_device_label.
// You can define custom methods on it to extend its functionality as you wish.
type entDeviceLabelDao struct {
	internalEntDeviceLabelDao
}

var (
	// EntDeviceLabel is globally public accessible object for table ent_device_label operations.
	EntDeviceLabel = entDeviceLabelDao{
		internal.NewEntDeviceLabelDao(),
	}
)

// Fill with you ideas below.
