// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalEntSysPostDao is internal type for wrapping internal DAO implements.
type internalEntSysPostDao = *internal.EntSysPostDao

// entSysPostDao is the data access object for table ent_sys_post.
// You can define custom methods on it to extend its functionality as you wish.
type entSysPostDao struct {
	internalEntSysPostDao
}

var (
	// EntSysPost is globally public accessible object for table ent_sys_post operations.
	EntSysPost = entSysPostDao{
		internal.NewEntSysPostDao(),
	}
)

// Fill with you ideas below.
