// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalEntRoleDao is internal type for wrapping internal DAO implements.
type internalEntRoleDao = *internal.EntRoleDao

// entRoleDao is the data access object for table ent_role.
// You can define custom methods on it to extend its functionality as you wish.
type entRoleDao struct {
	internalEntRoleDao
}

var (
	// EntRole is globally public accessible object for table ent_role operations.
	EntRole = entRoleDao{
		internal.NewEntRoleDao(),
	}
)

// Fill with you ideas below.
