// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalEntSysLoginLogDao is internal type for wrapping internal DAO implements.
type internalEntSysLoginLogDao = *internal.EntSysLoginLogDao

// entSysLoginLogDao is the data access object for table ent_sys_login_log.
// You can define custom methods on it to extend its functionality as you wish.
type entSysLoginLogDao struct {
	internalEntSysLoginLogDao
}

var (
	// EntSysLoginLog is globally public accessible object for table ent_sys_login_log operations.
	EntSysLoginLog = entSysLoginLogDao{
		internal.NewEntSysLoginLogDao(),
	}
)

// Fill with you ideas below.
