// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalEnvDao is internal type for wrapping internal DAO implements.
type internalEnvDao = *internal.EnvDao

// envDao is the data access object for table env.
// You can define custom methods on it to extend its functionality as you wish.
type envDao struct {
	internalEnvDao
}

var (
	// Env is globally public accessible object for table env operations.
	Env = envDao{
		internal.NewEnvDao(),
	}
)

// Fill with you ideas below.
