// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalFundingCardDao is internal type for wrapping internal DAO implements.
type internalFundingCardDao = *internal.FundingCardDao

// fundingCardDao is the data access object for table funding_card.
// You can define custom methods on it to extend its functionality as you wish.
type fundingCardDao struct {
	internalFundingCardDao
}

var (
	// FundingCard is globally public accessible object for table funding_card operations.
	FundingCard = fundingCardDao{
		internal.NewFundingCardDao(),
	}
)

// Fill with you ideas below.
