// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalInstallTaskLinkScriptDao is internal type for wrapping internal DAO implements.
type internalInstallTaskLinkScriptDao = *internal.InstallTaskLinkScriptDao

// installTaskLinkScriptDao is the data access object for table install_task_link_script.
// You can define custom methods on it to extend its functionality as you wish.
type installTaskLinkScriptDao struct {
	internalInstallTaskLinkScriptDao
}

var (
	// InstallTaskLinkScript is globally public accessible object for table install_task_link_script operations.
	InstallTaskLinkScript = installTaskLinkScriptDao{
		internal.NewInstallTaskLinkScriptDao(),
	}
)

// Fill with you ideas below.
