// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalInstallTaskLinkDeviceGroupDao is internal type for wrapping internal DAO implements.
type internalInstallTaskLinkDeviceGroupDao = *internal.InstallTaskLinkDeviceGroupDao

// installTaskLinkDeviceGroupDao is the data access object for table install_task_link_device_group.
// You can define custom methods on it to extend its functionality as you wish.
type installTaskLinkDeviceGroupDao struct {
	internalInstallTaskLinkDeviceGroupDao
}

var (
	// InstallTaskLinkDeviceGroup is globally public accessible object for table install_task_link_device_group operations.
	InstallTaskLinkDeviceGroup = installTaskLinkDeviceGroupDao{
		internal.NewInstallTaskLinkDeviceGroupDao(),
	}
)

// Fill with you ideas below.
