// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalKeywordDao is internal type for wrapping internal DAO implements.
type internalKeywordDao = *internal.KeywordDao

// keywordDao is the data access object for table keyword.
// You can define custom methods on it to extend its functionality as you wish.
type keywordDao struct {
	internalKeywordDao
}

var (
	// Keyword is globally public accessible object for table keyword operations.
	Keyword = keywordDao{
		internal.NewKeywordDao(),
	}
)

// Fill with you ideas below.
