// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalLeaseOrderDevicesDao is internal type for wrapping internal DAO implements.
type internalLeaseOrderDevicesDao = *internal.LeaseOrderDevicesDao

// leaseOrderDevicesDao is the data access object for table lease_order_devices.
// You can define custom methods on it to extend its functionality as you wish.
type leaseOrderDevicesDao struct {
	internalLeaseOrderDevicesDao
}

var (
	// LeaseOrderDevices is globally public accessible object for table lease_order_devices operations.
	LeaseOrderDevices = leaseOrderDevicesDao{
		internal.NewLeaseOrderDevicesDao(),
	}
)

// Fill with you ideas below.
