// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalMinerSessionDao is internal type for wrapping internal DAO implements.
type internalMinerSessionDao = *internal.MinerSessionDao

// minerSessionDao is the data access object for table miner_session.
// You can define custom methods on it to extend its functionality as you wish.
type minerSessionDao struct {
	internalMinerSessionDao
}

var (
	// MinerSession is globally public accessible object for table miner_session operations.
	MinerSession = minerSessionDao{
		internal.NewMinerSessionDao(),
	}
)

// Fill with you ideas below.
