// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalMinerLoginTaskDao is internal type for wrapping internal DAO implements.
type internalMinerLoginTaskDao = *internal.MinerLoginTaskDao

// minerLoginTaskDao is the data access object for table miner_login_task.
// You can define custom methods on it to extend its functionality as you wish.
type minerLoginTaskDao struct {
	internalMinerLoginTaskDao
}

var (
	// MinerLoginTask is globally public accessible object for table miner_login_task operations.
	MinerLoginTask = minerLoginTaskDao{
		internal.NewMinerLoginTaskDao(),
	}
)

// Fill with you ideas below.
