// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalMinerCommunityDao is internal type for wrapping internal DAO implements.
type internalMinerCommunityDao = *internal.MinerCommunityDao

// minerCommunityDao is the data access object for table miner_community.
// You can define custom methods on it to extend its functionality as you wish.
type minerCommunityDao struct {
	internalMinerCommunityDao
}

var (
	// MinerCommunity is globally public accessible object for table miner_community operations.
	MinerCommunity = minerCommunityDao{
		internal.NewMinerCommunityDao(),
	}
)

// Fill with you ideas below.
