// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalMinerCronTaskDao is internal type for wrapping internal DAO implements.
type internalMinerCronTaskDao = *internal.MinerCronTaskDao

// minerCronTaskDao is the data access object for table miner_cron_task.
// You can define custom methods on it to extend its functionality as you wish.
type minerCronTaskDao struct {
	internalMinerCronTaskDao
}

var (
	// MinerCronTask is globally public accessible object for table miner_cron_task operations.
	MinerCronTask = minerCronTaskDao{
		internal.NewMinerCronTaskDao(),
	}
)

// Fill with you ideas below.
