// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalMinerImportPhotoTaskLinkDeviceDao is internal type for wrapping internal DAO implements.
type internalMinerImportPhotoTaskLinkDeviceDao = *internal.MinerImportPhotoTaskLinkDeviceDao

// minerImportPhotoTaskLinkDeviceDao is the data access object for table miner_import_photo_task_link_device.
// You can define custom methods on it to extend its functionality as you wish.
type minerImportPhotoTaskLinkDeviceDao struct {
	internalMinerImportPhotoTaskLinkDeviceDao
}

var (
	// MinerImportPhotoTaskLinkDevice is globally public accessible object for table miner_import_photo_task_link_device operations.
	MinerImportPhotoTaskLinkDevice = minerImportPhotoTaskLinkDeviceDao{
		internal.NewMinerImportPhotoTaskLinkDeviceDao(),
	}
)

// Fill with you ideas below.
