// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalMinerTaskDao is internal type for wrapping internal DAO implements.
type internalMinerTaskDao = *internal.MinerTaskDao

// minerTaskDao is the data access object for table miner_task.
// You can define custom methods on it to extend its functionality as you wish.
type minerTaskDao struct {
	internalMinerTaskDao
}

var (
	// MinerTask is globally public accessible object for table miner_task operations.
	MinerTask = minerTaskDao{
		internal.NewMinerTaskDao(),
	}
)

// Fill with you ideas below.
