// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalMinerImportMobileTaskDao is internal type for wrapping internal DAO implements.
type internalMinerImportMobileTaskDao = *internal.MinerImportMobileTaskDao

// minerImportMobileTaskDao is the data access object for table miner_import_mobile_task.
// You can define custom methods on it to extend its functionality as you wish.
type minerImportMobileTaskDao struct {
	internalMinerImportMobileTaskDao
}

var (
	// MinerImportMobileTask is globally public accessible object for table miner_import_mobile_task operations.
	MinerImportMobileTask = minerImportMobileTaskDao{
		internal.NewMinerImportMobileTaskDao(),
	}
)

// Fill with you ideas below.
