// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalMinerImportPhotoTaskLinkJdGroupDao is internal type for wrapping internal DAO implements.
type internalMinerImportPhotoTaskLinkJdGroupDao = *internal.MinerImportPhotoTaskLinkJdGroupDao

// minerImportPhotoTaskLinkJdGroupDao is the data access object for table miner_import_photo_task_link_jd_group.
// You can define custom methods on it to extend its functionality as you wish.
type minerImportPhotoTaskLinkJdGroupDao struct {
	internalMinerImportPhotoTaskLinkJdGroupDao
}

var (
	// MinerImportPhotoTaskLinkJdGroup is globally public accessible object for table miner_import_photo_task_link_jd_group operations.
	MinerImportPhotoTaskLinkJdGroup = minerImportPhotoTaskLinkJdGroupDao{
		internal.NewMinerImportPhotoTaskLinkJdGroupDao(),
	}
)

// Fill with you ideas below.
