// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalMinerLoginRecodeDao is internal type for wrapping internal DAO implements.
type internalMinerLoginRecodeDao = *internal.MinerLoginRecodeDao

// minerLoginRecodeDao is the data access object for table miner_login_recode.
// You can define custom methods on it to extend its functionality as you wish.
type minerLoginRecodeDao struct {
	internalMinerLoginRecodeDao
}

var (
	// MinerLoginRecode is globally public accessible object for table miner_login_recode operations.
	MinerLoginRecode = minerLoginRecodeDao{
		internal.NewMinerLoginRecodeDao(),
	}
)

// Fill with you ideas below.
