// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalMinerEarningFlowDao is internal type for wrapping internal DAO implements.
type internalMinerEarningFlowDao = *internal.MinerEarningFlowDao

// minerEarningFlowDao is the data access object for table miner_earning_flow.
// You can define custom methods on it to extend its functionality as you wish.
type minerEarningFlowDao struct {
	internalMinerEarningFlowDao
}

var (
	// MinerEarningFlow is globally public accessible object for table miner_earning_flow operations.
	MinerEarningFlow = minerEarningFlowDao{
		internal.NewMinerEarningFlowDao(),
	}
)

// Fill with you ideas below.
