// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalMinerPlatformDao is internal type for wrapping internal DAO implements.
type internalMinerPlatformDao = *internal.MinerPlatformDao

// minerPlatformDao is the data access object for table miner_platform.
// You can define custom methods on it to extend its functionality as you wish.
type minerPlatformDao struct {
	internalMinerPlatformDao
}

var (
	// MinerPlatform is globally public accessible object for table miner_platform operations.
	MinerPlatform = minerPlatformDao{
		internal.NewMinerPlatformDao(),
	}
)

// Fill with you ideas below.
