// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalNicknameDao is internal type for wrapping internal DAO implements.
type internalNicknameDao = *internal.NicknameDao

// nicknameDao is the data access object for table nickname.
// You can define custom methods on it to extend its functionality as you wish.
type nicknameDao struct {
	internalNicknameDao
}

var (
	// Nickname is globally public accessible object for table nickname operations.
	Nickname = nicknameDao{
		internal.NewNicknameDao(),
	}
)

// Fill with you ideas below.
