// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalPicDao is internal type for wrapping internal DAO implements.
type internalPicDao = *internal.PicDao

// picDao is the data access object for table pic.
// You can define custom methods on it to extend its functionality as you wish.
type picDao struct {
	internalPicDao
}

var (
	// Pic is globally public accessible object for table pic operations.
	Pic = picDao{
		internal.NewPicDao(),
	}
)

// Fill with you ideas below.
