// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalProjectListDao is internal type for wrapping internal DAO implements.
type internalProjectListDao = *internal.ProjectListDao

// projectListDao is the data access object for table project_list.
// You can define custom methods on it to extend its functionality as you wish.
type projectListDao struct {
	internalProjectListDao
}

var (
	// ProjectList is globally public accessible object for table project_list operations.
	ProjectList = projectListDao{
		internal.NewProjectListDao(),
	}
)

// Fill with you ideas below.
