// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalRaiseTaskInstanceDao is internal type for wrapping internal DAO implements.
type internalRaiseTaskInstanceDao = *internal.RaiseTaskInstanceDao

// raiseTaskInstanceDao is the data access object for table raise_task_instance.
// You can define custom methods on it to extend its functionality as you wish.
type raiseTaskInstanceDao struct {
	internalRaiseTaskInstanceDao
}

var (
	// RaiseTaskInstance is globally public accessible object for table raise_task_instance operations.
	RaiseTaskInstance = raiseTaskInstanceDao{
		internal.NewRaiseTaskInstanceDao(),
	}
)

// Fill with you ideas below.
