// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalRaiseTaskLinkKeywordDao is internal type for wrapping internal DAO implements.
type internalRaiseTaskLinkKeywordDao = *internal.RaiseTaskLinkKeywordDao

// raiseTaskLinkKeywordDao is the data access object for table raise_task_link_keyword.
// You can define custom methods on it to extend its functionality as you wish.
type raiseTaskLinkKeywordDao struct {
	internalRaiseTaskLinkKeywordDao
}

var (
	// RaiseTaskLinkKeyword is globally public accessible object for table raise_task_link_keyword operations.
	RaiseTaskLinkKeyword = raiseTaskLinkKeywordDao{
		internal.NewRaiseTaskLinkKeywordDao(),
	}
)

// Fill with you ideas below.
