// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalRaiseTaskLinkWordsGroupDao is internal type for wrapping internal DAO implements.
type internalRaiseTaskLinkWordsGroupDao = *internal.RaiseTaskLinkWordsGroupDao

// raiseTaskLinkWordsGroupDao is the data access object for table raise_task_link_words_group.
// You can define custom methods on it to extend its functionality as you wish.
type raiseTaskLinkWordsGroupDao struct {
	internalRaiseTaskLinkWordsGroupDao
}

var (
	// RaiseTaskLinkWordsGroup is globally public accessible object for table raise_task_link_words_group operations.
	RaiseTaskLinkWordsGroup = raiseTaskLinkWordsGroupDao{
		internal.NewRaiseTaskLinkWordsGroupDao(),
	}
)

// Fill with you ideas below.
