// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalRaiseTaskDao is internal type for wrapping internal DAO implements.
type internalRaiseTaskDao = *internal.RaiseTaskDao

// raiseTaskDao is the data access object for table raise_task.
// You can define custom methods on it to extend its functionality as you wish.
type raiseTaskDao struct {
	internalRaiseTaskDao
}

var (
	// RaiseTask is globally public accessible object for table raise_task operations.
	RaiseTask = raiseTaskDao{
		internal.NewRaiseTaskDao(),
	}
)

// Fill with you ideas below.
