// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalRechargeListDao is internal type for wrapping internal DAO implements.
type internalRechargeListDao = *internal.RechargeListDao

// rechargeListDao is the data access object for table recharge_list.
// You can define custom methods on it to extend its functionality as you wish.
type rechargeListDao struct {
	internalRechargeListDao
}

var (
	// RechargeList is globally public accessible object for table recharge_list operations.
	RechargeList = rechargeListDao{
		internal.NewRechargeListDao(),
	}
)

// Fill with you ideas below.
