// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalScriptOpDao is internal type for wrapping internal DAO implements.
type internalScriptOpDao = *internal.ScriptOpDao

// scriptOpDao is the data access object for table script_op.
// You can define custom methods on it to extend its functionality as you wish.
type scriptOpDao struct {
	internalScriptOpDao
}

var (
	// ScriptOp is globally public accessible object for table script_op operations.
	ScriptOp = scriptOpDao{
		internal.NewScriptOpDao(),
	}
)

// Fill with you ideas below.
