// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalScriptLinkAppLabelDao is internal type for wrapping internal DAO implements.
type internalScriptLinkAppLabelDao = *internal.ScriptLinkAppLabelDao

// scriptLinkAppLabelDao is the data access object for table script_link_app_label.
// You can define custom methods on it to extend its functionality as you wish.
type scriptLinkAppLabelDao struct {
	internalScriptLinkAppLabelDao
}

var (
	// ScriptLinkAppLabel is globally public accessible object for table script_link_app_label operations.
	ScriptLinkAppLabel = scriptLinkAppLabelDao{
		internal.NewScriptLinkAppLabelDao(),
	}
)

// Fill with you ideas below.
