// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalScriptLinkAppGroupDao is internal type for wrapping internal DAO implements.
type internalScriptLinkAppGroupDao = *internal.ScriptLinkAppGroupDao

// scriptLinkAppGroupDao is the data access object for table script_link_app_group.
// You can define custom methods on it to extend its functionality as you wish.
type scriptLinkAppGroupDao struct {
	internalScriptLinkAppGroupDao
}

var (
	// ScriptLinkAppGroup is globally public accessible object for table script_link_app_group operations.
	ScriptLinkAppGroup = scriptLinkAppGroupDao{
		internal.NewScriptLinkAppGroupDao(),
	}
)

// Fill with you ideas below.
