// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalSiteMessageDao is internal type for wrapping internal DAO implements.
type internalSiteMessageDao = *internal.SiteMessageDao

// siteMessageDao is the data access object for table site_message.
// You can define custom methods on it to extend its functionality as you wish.
type siteMessageDao struct {
	internalSiteMessageDao
}

var (
	// SiteMessage is globally public accessible object for table site_message operations.
	SiteMessage = siteMessageDao{
		internal.NewSiteMessageDao(),
	}
)

// Fill with you ideas below.
