// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalSmsChartLogDao is internal type for wrapping internal DAO implements.
type internalSmsChartLogDao = *internal.SmsChartLogDao

// smsChartLogDao is the data access object for table sms_chart_log.
// You can define custom methods on it to extend its functionality as you wish.
type smsChartLogDao struct {
	internalSmsChartLogDao
}

var (
	// SmsChartLog is globally public accessible object for table sms_chart_log operations.
	SmsChartLog = smsChartLogDao{
		internal.NewSmsChartLogDao(),
	}
)

// Fill with you ideas below.
