// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalSpecialOperateDao is internal type for wrapping internal DAO implements.
type internalSpecialOperateDao = *internal.SpecialOperateDao

// specialOperateDao is the data access object for table special_operate.
// You can define custom methods on it to extend its functionality as you wish.
type specialOperateDao struct {
	internalSpecialOperateDao
}

var (
	// SpecialOperate is globally public accessible object for table special_operate operations.
	SpecialOperate = specialOperateDao{
		internal.NewSpecialOperateDao(),
	}
)

// Fill with you ideas below.
