// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalSysAuthRule20240821Dao is internal type for wrapping internal DAO implements.
type internalSysAuthRule20240821Dao = *internal.SysAuthRule20240821Dao

// sysAuthRule20240821Dao is the data access object for table sys_auth_rule_20240821.
// You can define custom methods on it to extend its functionality as you wish.
type sysAuthRule20240821Dao struct {
	internalSysAuthRule20240821Dao
}

var (
	// SysAuthRule20240821 is globally public accessible object for table sys_auth_rule_20240821 operations.
	SysAuthRule20240821 = sysAuthRule20240821Dao{
		internal.NewSysAuthRule20240821Dao(),
	}
)

// Fill with you ideas below.
