// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalTaskLinkDeviceDao is internal type for wrapping internal DAO implements.
type internalTaskLinkDeviceDao = *internal.TaskLinkDeviceDao

// taskLinkDeviceDao is the data access object for table task_link_device.
// You can define custom methods on it to extend its functionality as you wish.
type taskLinkDeviceDao struct {
	internalTaskLinkDeviceDao
}

var (
	// TaskLinkDevice is globally public accessible object for table task_link_device operations.
	TaskLinkDevice = taskLinkDeviceDao{
		internal.NewTaskLinkDeviceDao(),
	}
)

// Fill with you ideas below.
