// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalTaskLinkScriptDao is internal type for wrapping internal DAO implements.
type internalTaskLinkScriptDao = *internal.TaskLinkScriptDao

// taskLinkScriptDao is the data access object for table task_link_script.
// You can define custom methods on it to extend its functionality as you wish.
type taskLinkScriptDao struct {
	internalTaskLinkScriptDao
}

var (
	// TaskLinkScript is globally public accessible object for table task_link_script operations.
	TaskLinkScript = taskLinkScriptDao{
		internal.NewTaskLinkScriptDao(),
	}
)

// Fill with you ideas below.
