// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalTpContentDao is internal type for wrapping internal DAO implements.
type internalTpContentDao = *internal.TpContentDao

// tpContentDao is the data access object for table tp_content.
// You can define custom methods on it to extend its functionality as you wish.
type tpContentDao struct {
	internalTpContentDao
}

var (
	// TpContent is globally public accessible object for table tp_content operations.
	TpContent = tpContentDao{
		internal.NewTpContentDao(),
	}
)

// Fill with you ideas below.
