// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalWordsGroupDao is internal type for wrapping internal DAO implements.
type internalWordsGroupDao = *internal.WordsGroupDao

// wordsGroupDao is the data access object for table words_group.
// You can define custom methods on it to extend its functionality as you wish.
type wordsGroupDao struct {
	internalWordsGroupDao
}

var (
	// WordsGroup is globally public accessible object for table words_group operations.
	WordsGroup = wordsGroupDao{
		internal.NewWordsGroupDao(),
	}
)

// Fill with you ideas below.
