// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sms_backend/internal/dao/internal"
)

// internalWordsGroupDetailsDao is internal type for wrapping internal DAO implements.
type internalWordsGroupDetailsDao = *internal.WordsGroupDetailsDao

// wordsGroupDetailsDao is the data access object for table words_group_details.
// You can define custom methods on it to extend its functionality as you wish.
type wordsGroupDetailsDao struct {
	internalWordsGroupDetailsDao
}

var (
	// WordsGroupDetails is globally public accessible object for table words_group_details operations.
	WordsGroupDetails = wordsGroupDetailsDao{
		internal.NewWordsGroupDetailsDao(),
	}
)

// Fill with you ideas below.
